name: publish podspecs
on:
  release:
    types: [ published ]

jobs:
  publish-podspecs:
    runs-on: macos-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Push Podspecs
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        echo ${{ steps.get_release.outputs.tag_name }} > version 
        pod trunk push CZiti-iOS.podspec
        pod trunk push CZiti-macOS.podspec

  build-docs:
    runs-on: macos-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      with:
        submodules: true

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2.1'

    - name: Get Jazzy
      run: gem install jazzy

    - name: Build C SDK
      run: |
        cmake -DMBEDTLS_FATAL_WARNINGS:BOOL=OFF -DEXCLUDE_PROGRAMS=ON -S ./deps/ziti-tunnel-sdk-c -B ./deps/ziti-tunnel-sdk-c/build-macosx-x86_64
        cmake --build ./deps/ziti-tunnel-sdk-c/build-macosx-x86_64

    - name: Gen Docs
      run: |
        rm *.podspec
        jazzy --hide-documentation-coverage -x '-arch,x86_64,-scheme,CZiti-macOS,-sdk,macosx' -m CZiti
        tar -cvzf ./ziti-sdk-swift-docs.tgz -C ./docs .

    - name: Upload Docs
      uses: actions/upload-artifact@v3
      with:
        name: ziti-sdk-swift-docs
        path: ziti-sdk-swift-docs.tgz

  publish-docs:
    runs-on: ubuntu-latest
    needs: [publish-podspecs, build-docs]
    concurrency: ci-${{ github.ref }}
    - name: Download Docs
      uses: actions/download-artifact@v3
      with:
        name: ziti-sdk-swift-docs

    - name: Extract Docs
      run: |
        mkdir ./docs
        tar -xvzf ./ziti-sdk-swift-docs.tgz -C ./docs .

    - name: Publish Docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
